.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. eurodollar_qt test_eurodollar_qt
clean: FORCE
	$(MAKE) -C .. eurodollar_qt_clean test_eurodollar_qt_clean
check: FORCE
	$(MAKE) -C .. test_eurodollar_qt_check
eurodollar-qt eurodollar-qt.exe: FORCE
	 $(MAKE) -C .. eurodollar_qt
